# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=50)),
                ('label', models.CharField(default='label', max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('remove', models.BooleanField(default=False)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_member', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
